/**
 * HTML report — a rendering of exactly one Evidence Bundle, no extra
 * inference. Colors encode the deterministic label; every claim in the
 * document is traceable to a bundle field (rendered inline for audit).
 */

import type { EvidenceBundle } from '@canary-rn/evidence-schema';

const COLORS: Record<string, string> = {
  PASS: '#1a7f37',
  CONFIRMED_REGRESSION: '#b91c1c',
  PRE_EXISTING_FAILURE: '#9a3412',
  FLAKY: '#a16207',
  INFRASTRUCTURE_FAILURE: '#4b5563',
  INCONCLUSIVE: '#4b5563',
};

function esc(s: unknown): string {
  return String(s ?? '').replace(/[&<>"]/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] ?? c);
}

export function renderHtml(bundle: EvidenceBundle, extras?: { failingTestNames?: string[] }): string {
  const color = COLORS[bundle.classification.label] ?? '#000';
  const rows = bundle.rounds.map((r) => `
    <tr class="${r.arm}">
      <td>${esc(r.arm)} #${r.round}</td>
      <td class="${r.exitCode === 0 ? 'ok' : 'bad'}">${r.exitCode}</td>
      <td>${r.hasRunnerSummary ? 'yes' : 'NO'}</td>
      <td>${r.killedByTimeout ? 'killed' : '—'}</td>
      <td title="raw stdout ${esc(r.rawStdoutSha256)}">${esc(r.normalizedStdoutSha256.slice(0, 16))}…</td>
      <td>${r.durationMs} ms</td>
      <td><a href="${esc(r.logPath)}">${esc(r.logPath)}</a></td>
    </tr>`).join('');

  const drift = bundle.treeComparison;
  // Audit F12: failing-test identities come from the BUNDLE ITSELF (F13
  // persisted them per candidate round) — not from an `extras` argument no
  // caller ever passed. extras remains only as an explicit override.
  const derivedFailing = bundle.rounds
    .filter((r) => r.arm === 'candidate')
    .flatMap((r) => r.failingTestNames ?? []);
  const failing = [...new Set(extras?.failingTestNames ?? derivedFailing)].sort()
    .map((t) => `<li><code>${esc(t)}</code></li>`).join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Canary evidence — ${esc(bundle.experimentId)}</title>
<style>
 body{font:14px/1.5 ui-sans-serif,system-ui,sans-serif;margin:2rem auto;max-width:60rem;color:#111}
 .verdict{padding:1rem 1.25rem;border-radius:8px;color:#fff;background:${color};font-size:1.3rem;font-weight:700}
 h1{font-size:1.4rem} h2{font-size:1.05rem;margin-top:2rem}
 table{border-collapse:collapse;width:100%} td,th{border:1px solid #ddd;padding:.35rem .6rem;text-align:left}
 tr.baseline td:first-child{border-left:4px solid #1a7f37} tr.candidate td:first-child{border-left:4px solid #b91c1c}
 .ok{color:#1a7f37;font-weight:700}.bad{color:#b91c1c;font-weight:700}
 code{background:#f3f4f6;padding:.1rem .35rem;border-radius:4px}
 .grid{display:grid;grid-template-columns:14rem 1fr;gap:.2rem .8rem}
 .grid b{font-weight:600;color:#374151}
 footer{margin-top:3rem;color:#6b7280;font-size:.85rem;border-top:1px solid #eee;padding-top:1rem}
</style></head><body>
<div class="verdict">${esc(bundle.classification.label)} — rule ${esc(bundle.classification.rule)}</div>
<p>${esc(bundle.classification.reason)} · reproduced ${esc(bundle.classification.reproductionCount)}×</p>

<h1>Experiment ${esc(bundle.experimentId)}</h1>
<div class="grid">
  <b>dependency</b><span><code>${esc(bundle.dependency.package)}: ${esc(bundle.dependency.baselineVersion)} → ${esc(bundle.dependency.candidateVersion)}</code></span>
  <b>downstream</b><span><a href="${esc(bundle.downstream.repositoryUrl)}">${esc(bundle.downstream.repositoryUrl)}</a></span>
  <b>commit</b><span><code>${esc(bundle.downstream.commitSha)}</code> (${esc(bundle.downstream.fetchMethod)})</span>
  <b>tarball sha256</b><span><code>${esc(bundle.downstream.tarballSha256.slice(0, 32))}…</code></span>
  <b>environment</b><span>node ${esc(bundle.environment.nodeVersion)} · npm ${esc(bundle.environment.npmVersion)} · ${esc(bundle.environment.platform)}/${esc(bundle.environment.arch)}</span>
  <b>overrides</b><span>${esc(JSON.stringify(bundle.environment.toolchainOverrides))}</span>
  <b>run</b><span>${esc(bundle.runId)} · ${esc(bundle.createdAt)} · canary ${esc(bundle.canaryVersion)}</span>
</div>

<h2>Rounds</h2>
<table><thead><tr><th>arm</th><th>exit</th><th>summary</th><th>timeout</th><th>normalized stdout</th><th>duration</th><th>log</th></tr></thead>
<tbody>${rows}</tbody></table>

<h2>Environment equivalence</h2>
<p>Dependency-tree drift confined to <code>${esc(bundle.dependency.package)}</code>:
<b class="${drift.driftConfinedToDependency ? 'ok' : 'bad'}">${drift.driftConfinedToDependency ? 'YES — arms differ only by the studied dependency' : 'NO — arms differ beyond the dependency (results not trustworthy)'}</b></p>

${failing ? `<h2>Failing downstream tests (candidate)</h2><ul>${failing}</ul>` : ''}

${bundle.ai ? `<h2>AI annotation (non-authoritative)</h2><p><i>${esc(bundle.ai.summary)}</i> — ${esc(bundle.ai.provider)}, attached ${esc(bundle.ai.attachedAt)}. This section cannot and did not influence the classification above.</p>` : ''}

<footer>Generated by Canary ${esc(bundle.canaryVersion)} from evidence schema v${esc(bundle.schemaVersion)}. The JSON bundle beside this file is the authoritative artifact; hashes are verifiable against the raw logs in the run's artifacts directory.</footer>
</body></html>`;
}
